#map content
mapdesc = { (0,0) : "You stand amongst tall green grass",
            (0,1) : "You can see a mountain in the distance",
            (0,2) : "You stand amongst tall green grass",
            (0,3) : "You are stood in a wet bog",
            (1,0) : "You stand upon a hill.",
            (1,1) : "You stand upon a hill.",
            (1,2) : "You are in a meadow surrounded by wild flowers",
            (1,3) : "You are sat beside a tranquil lazy stream",
            (2,0) : "You are surrounded by forest.",
            (2,1) : "You are surrounded by forest.",
            (2,2) : "You are deep in the forest, dark and musty.",
            (2,3) : "You are walking along a dusty trail.",
            (3,0) : "You are at a ford across a shallow river.",
            (3,1) : "You are atop the highest hill and can see for miles.",
            (3,2) : "You are at the collapsed entrace to a mine.",
            (3,3) : "You in front of a huge boulder.",
}
monsters = { "Imp" : 3,
             "Goblin" : 2,
             "Wobuffet" : 4,
             "Krampus" : 7,
}

maptypelist = ['hills','grass','meadow','plain','trail','river','stream','lake','tophill','cave','boulder']
maptypedesc = {'hills' : "You stand upon a hill.",
               'grass' : "You stand amongst tall green grass",
               'meadow': "You are in a meadow surrounded by wild flowers" ,
               'plain' : "You stand upon a wide open plain",
               'trail' : "You are walking along a dusty trail.",
               'river' : "You are walking alongside a wide river",
               'stream': "You are sat beside a tranquil lazy stream",
               'lake' : "You are beside a wide open lake.",
               'tophill' : "You are atop the highest hill and can see for miles.",
               'cave' : "You are at the collapsed entrace to a mine.",
               'boulder' : "You in front of a huge boulder.",
               'bog' : "You are stood in a wet bog"}
